import sqlite3
from pathlib import Path

db_path = Path(__file__).parent / "courses.db"

MAJORS = [
    "Academic Spanish for Heritage Speakers - Campus Certificate",
    "Accounting - BS",
    "Accounting - Minor",
    "Acting - BFA",
    "Anthropology - BA with a Major",
    "Anthropology - Minor",
    "Applied Psychology - BA with a Major",
    "Arabic - Minor",
    "Architectural Studies - BA",
    "Architectural Studies - Minor",
    "Architecture - BS",
    "Art - BFA",
    "Art - Minor",
    "Art Education - BFA",
    "Art History - BA",
    "Art History - Minor",
    "Bachelor of Business Administration Completion Program (on-campus)",
    "Bachelor of Business Administration Completion Program (online)",
    "Biochemistry - BS",
    "Biological Sciences - BS with a Major",
    "Evolution, Ecology and Environmental Biology Concentration",
    "General Biology Concentration",
    "Molecular, Cellular and Organismal Biology Concentration",
    "Biological Sciences - Minor",
    "Biomedical Engineering - BS",
    "Biomedical Engineering - Minor",
    "Black Studies - BA with a Major",
    "Black Studies - Minor",
    "Business Adminstration - Minor",
    "Business Analytics - Minor",
    "Central and Eastern European Studies - BA with a Major",
    "Central and Eastern European Concentration",
    "Polish Studies Concentration",
    "Russian Studies Concentration",
    "Central and Eastern European Studies - Minor",
    "Chemical Engineering - BS",
    "Biochemical Engineering Concentration",
    "Energy and Environment Concentration",
    "Entrepreneurship Concentration",
    "Nanotechnology Concentration",
    "Polymers and Molecular Engineering Concentration",
    "Process Automation Concentration",
    "Chemical Engineering - Joint BS/MS",
    "Chemical Engineering - Minor",
    "Chemistry - BA with a Major",
    "Chemistry - BS",
    "Chemistry - Minor",
    "Chinese - Minor",
    "Civic Analytics - Minor",
    "Civil Engineering - BS",
    "Civil Engineering - Minor",
    "Classical Studies - BA with a Major",
    "Classical Studies - Minor",
    "Co-Operative Career Experience - Campus Certificate",
    "Communication - BA with a Major",
    "Communication - Minor",
    "Comparative Cultural Studies - Minor",
    "Computer Engineering - BS",
    "Computer Engineering - Minor",
    "Computer Science - BS",
    "Computer Systems Concentration",
    "Human-Centered Computing Concentration",
    "Software Engineering Concentration",
    "Computer Science - Joint BS/MS",
    "Computer Science - Minor",
    "Computer Science and Design - BS",
    "Computer Science and Linguistics - BS",
    "Computer Science and Philosophy - BS",
    "Criminology Law and Justice - BA with a Major",
    "Criminology Law and Justice - Minor",
    "Data Science - BS",
    "Bioinformatics Concentration",
    "Business Analytics Concentration",
    "Computer Science Concentration",
    "Data Processing Science and Engineering Concentration",
    "Health Data Science Concentration",
    "Industrial Engineering Concentration",
    "Social Technology Studies Concentration",
    "Statistics Concentration",
    "Urban Planning and Public Affairs Concentration",
    "Design Studies - BA",
    "Disability Inclusion - Minor",
    "Disability and Human Development - BS",
    "Earth and Environmental Sciences - BS with a Major",
    "Earth and Environmental Sciences - Minor",
    "Economics - BA with a Major",
    "Economics - Minor",
    "Education - Minor",
    "Electrical Engineering - BS",
    "Electrical Engineering - Minor",
    "Electrical and Computer Engineering -Joint Degrees:",
    "Computer Engineering/Electrical and Computer Engineering - Joint BS/MS",
    "Electrical Engineering/ Electrical and Computer Engineering - Joint BS/MS",
    "Engineering Physics/ Electrical and Computer Engineering - Joint BS/MS",
    "Engineering Management - BS",
    "Engineering Physics - BS",
    "English - BA with a Major",
    "Literatures in English Concentration",
    "Creative Writing Concentration (Fiction-Poetry-or Nonfiction)",
    "Film-Media-Performance-and Pop Culture Concentration",
    "Professional Writing and Publishing Concentration",
    "Race-Gender and Sexuality-and Multiethnic English Studies Concentration",
    "Rhetoric-Public Engagement- and Language Studies Concentration",
    "English - Minor",
    "Entrepreneurship - BS",
    "Entrepreneurship - Minor",
    "Environmental Engineering - BS",
    "Environmental Engineering - Minor",
    "Finance - BS",
    "Finance - Minor",
    "Food Science - Minor",
    "French and Francophone Studies - BA with a Major",
    "French and Francophone Studies - Minor",
    "Gender and Women's Studies - Minor",
    "Gender and Women’s Studies - BA with a Major",
    "Geographic Information Systems - Minor",
    "German Language - Campus Certificate",
    "Germanic Studies - BA with a Major",
    "Germanic Studies - Minor",
    "Global Asian Studies - BA with a Major",
    "Global Asian Studies - Minor",
    "Global Middle East Studies - Minor",
    "Graphic Design - BDes",
    "Health Culture and Society - Campus Certificate",
    "Health Information Management - BS",
    "Health Information Management - Minor",
    "Health Information Management/Health Informatics - Joint BS/MS",
    "History - BA with a Major",
    "History - Minor",
    "Human Development and Learning - BA",
    "Human Resource Management - BS",
    "Human Resource Management - Minor",
    "Industrial Design - BDes",
    "Industrial Engineering - BS",
    "Industrial Engineering - Joint Degrees:",
    "BS/MS in Industrial Engineering",
    "BS/MS in Mechanical Engineering",
    "Industrial Engineering - Minor",
    "Information Technology - Minor",
    "Information and Decision Sciences - BS",
    "Instructional Design and Training - Minor",
    "Integrated Health Studies - BS with a Major",
    "Behavioral Health Concentration",
    "Health and Science Concentration",
    "Interdisciplinary Education in the Arts - BA",
    "International Business - Minor",
    "International Studies - Minor",
    "Italian and Italian American Studies - Minor",
    "Jazz Studies - BMus",
    "Kinesiology - BS",
    "Kinesiology - Minor",
    "Latin American and Latino Studies - BA with a Major",
    "Latin American and Latino Studies - Minor",
    "Law and Society - Minor",
    "Leadership - Minor",
    "Liberal Studies - BA with a Major",
    "Life Science Visualization - Minor",
    "Linguistics - BA with a Major",
    "Linguistics - Minor",
    "Logic Argumentation and Writing - Minor",
    "Management - BS",
    "Management Information Systems - Minor",
    "Marketing - BS",
    "Marketing - Minor",
    "Materials Engineering - Minor",
    "Mathematics - BS with a Major",
    "Mathematics - Minor",
    "Mathematics and Computer Science - BS with a Major",
    "Algorithms and Theory Concentration",
    "Computational Mathematics Concentration",
    "Mathematics and Computer Science - Minor",
    "Mechanical Engineering - BS",
    "Mechanical Engineering - Joint Degrees:",
    "BS/MS in Mechanical Engineering",
    "BS/MS in Industrial Engineering",
    "BS/Master of Energy Engineering",
    "Mechanical Engineering - Minor",
    "Moving Image Arts - Minor",
    "Museum and Exhibition Studies - Minor",
    "Music - BA",
    "Music - Minor",
    "Music Business - BA",
    "Music Education - BMus",
    "Neuroscience - BS",
    "Nonprofit Management - Minor",
    "Nursing - BS",
    "Nutrition - BS",
    "Nutrition Science Concentration",
    "Nutrition - Minor",
    "Performance - BMus",
    "Pharmaceutical Sciences - BS",
    "Pharmacy - Doctor",
    "Philosophy - BA with a Major",
    "Philosophy - Minor",
    "Physics - BA with a Major",
    "Physics - BS",
    "Physics - Minor",
    "Polish Language - Campus Certificate",
    "Polish Studies - Minor",
    "Political Science - BA with a Major",
    "Law and Courts Concentration",
    "Urban Politics Concentration",
    "Political Science - Minor",
    "Pre-Dentistry",
    "Pre-Health Information Management",
    "Pre-Law",
    "Pre-Medicine",
    "Pre-Nursing",
    "Pre-Nutrition",
    "Pre-Occupational Therapy (AHS)",
    "Pre-Occupational Therapy (LAS)",
    "Pre-Pharmacy",
    "Pre-Physical Therapy (AHS)",
    "Pre-Physical Therapy (LAS)",
    "Pre-Public Health (SPH)",
    "Pre-Veterinary Medicine",
    "Professional Sales and Relationship Management - Minor",
    "Professional Writing - Minor",
    "Psychology - BS with a Major",
    "Psychology - Minor",
    "Public Health - BA",
    "Public Health - BS",
    "Public Health - Joint Degrees:",
    "BA/MPH-Community Health Sciences Concentration",
    "BA/MPH-Environmental and Occupational Health Sciences Concentration",
    "BA/MPH-Epidemiology Concentration",
    "BA/MPH-Health Policy and Administration Concentration",
    "BS/MPH-Community Health Sciences Concentration",
    "BS/MPH-Environmental and Occupational Health Sciences Concentration",
    "BS/MPH-Epidemiology Concentration",
    "BS/MPH-Health Policy and Administration Concentration",
    "Public Health - Minor",
    "Public Policy - BA",
    "Public Policy - Joint Degrees with BA:",
    "Master of Public Administration",
    "Master of Public Policy",
    "Master of Urban Planning and Policy",
    "MS in Civic Analytics",
    "Public Policy - Minor",
    "RN/BSN Completion Program",
    "Real Estate - BS",
    "Real Estate - Minor",
    "Rehabilitation Sciences - BS",
    "Religious Studies - Minor",
    "Research Design and Data Analysis - Minor",
    "Russian Language - Campus Certificate",
    "Russian Studies - Minor",
    "Social Justice - Minor",
    "Sociology - BA with a Major",
    "Data and Analytics Concentration",
    "Health and Medicine Concentration",
    "Professions Occupations and Work Concentration",
    "Sociology for Social Work Concentration",
    "Sociology - Minor",
    "Spanish - BA with a Major",
    "Spanish for the Professions Concentration",
    "Spanish - Minor",
    "Spanish for the Professions - Minor",
    "Sports Management - Minor",
    "Statistics - BS with a Major",
    "Statistical Theory and Methods Concentration",
    "Applied Statistics Concentration",
    "Supply Chain and Operations Management - Minor",
    "Sustainable Cities - Minor",
    "Teaching of English - BA",
    "Teaching of English - Minor",
    "Teaching of French - BA",
    "Teaching of German - BA",
    "Teaching of History - BA",
    "Teaching of Mathematics - BS",
    "Teaching of Spanish - BA",
    "Theatre - Minor",
    "Theatre Design Production and Technology - BA",
    "Theatre and Performance - BA",
    "Urban Education - BA",
    "Urban Studies - BA",
    "Urban Studies - Joint Degrees with BA:",
    "Master of Public Administration",
    "Master of Public Policy",
    "Master of Urban Planning and Policy",
    "MS in Civic Analytics",
    "Urban Studies - Minor",
]

def main():
    conn = sqlite3.connect(db_path)
    cur = conn.cursor()

    # Create table
    cur.execute("""
    CREATE TABLE IF NOT EXISTS majors (
        major_id INTEGER PRIMARY KEY AUTOINCREMENT,
        name TEXT NOT NULL UNIQUE
    )
    """)

    # Insert all (ignore duplicates safely)
    cur.executemany(
        "INSERT OR IGNORE INTO majors(name) VALUES (?)",
        [(m.strip(),) for m in MAJORS if m.strip()]
    )

    conn.commit()

    # quick count
    cur.execute("SELECT COUNT(*) FROM majors;")
    print("✅ majors rows:", cur.fetchone()[0])

    conn.close()

if __name__ == "__main__":
    main()
